services:
  - type: web
    name: ashray-portfolio
    env: node
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
      - key: NODE_ENV
        value: production
    plan: free