/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fltkoiksvjgnfpulzwar"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsdGtvaWtzdmpnbmZwdWx6d2FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NzU4OTQsImV4cCI6MjA3MTQ1MTg5NH0.Q-Psu0-1F2xAnyQd3bRETBl8kbBdvkOj3KN9qFoniOc"